defmodule Anvil.Repo.Migrations.ForeignKeysAndConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:prompts, "prompts_prompt_set_id_fkey")

    alter table(:prompts) do
      modify :prompt_set_id,
             references(:prompt_sets,
               column: :id,
               name: "prompts_prompt_set_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    drop constraint(:prompt_sets, "prompt_sets_project_id_fkey")

    alter table(:prompt_sets) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "prompt_sets_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    drop constraint(:prompt_set_versions, "prompt_set_versions_prompt_set_id_fkey")

    alter table(:prompt_set_versions) do
      modify :prompt_set_id,
             references(:prompt_sets,
               column: :id,
               name: "prompt_set_versions_prompt_set_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end
  end

  def down do
    drop constraint(:prompt_set_versions, "prompt_set_versions_prompt_set_id_fkey")

    alter table(:prompt_set_versions) do
      modify :prompt_set_id,
             references(:prompt_sets,
               column: :id,
               name: "prompt_set_versions_prompt_set_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:prompt_sets, "prompt_sets_project_id_fkey")

    alter table(:prompt_sets) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "prompt_sets_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:prompts, "prompts_prompt_set_id_fkey")

    alter table(:prompts) do
      modify :prompt_set_id,
             references(:prompt_sets,
               column: :id,
               name: "prompts_prompt_set_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
